/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Classes.ClsCandidato;
import Classes.ClsElecciones;
import Classes.ClsMensaje;
import Controller.CtlCandidato;
import Controller.CtlEleccion;
import Controller.CtlVotar;
import java.util.LinkedList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class FrameVotar extends javax.swing.JFrame {

    CtlEleccion controlador;
    CtlVotar controladorVoto;
    CtlEleccion controladorcandidato;
    ClsMensaje mensaje1;
    FrameMenu menu;

    /**
     * Creates new form Votar
     */
    public FrameVotar(FrameMenu menu) {
        initComponents();
        this.menu = menu;
        this.menu.setVisible(false);

        this.controlador = new CtlEleccion();
        this.controladorcandidato = new CtlEleccion();
        this.controladorVoto = new CtlVotar();

        //this.mensaje1 = new ClsMensaje();
        this.ObtenerEleccionesA();
        this.ObtenerInscritos();
    }

    public void ObtenerInscritos() {

        String[] y = this.comboEleccionesAbiertas.getSelectedItem().toString().split("-", 2);
        String h = y[0];

        LinkedList<ClsCandidato> inscritos = this.controladorcandidato.ObtenerInscritos(h);

        this.ActualizarListaInscritos(inscritos);

    }

    public void ActualizarListaInscritos(LinkedList<ClsCandidato> lista) {
        DefaultTableModel model = (DefaultTableModel) this.ListaCandidatos.getModel();
        model.setRowCount(0);
        for (ClsCandidato inscrip : lista) {
            Object[] row = {inscrip.getNumeroDoc(), inscrip.getNombre(), inscrip.getPartidoPolitico()};
            model.addRow(row);
        }

    }

    public void ObtenerEleccionesA() {

        LinkedList<ClsElecciones> elecciones = this.controlador.ObtenerEleccionesA();

        DefaultComboBoxModel model = (DefaultComboBoxModel) this.comboEleccionesAbiertas.getModel();
        model.removeAllElements();

        for (ClsElecciones eleccion : elecciones) {
            model.addElement(eleccion.getId() + "-" + eleccion.getNombre() + " " + eleccion.getTipo());

        }

        this.comboEleccionesAbiertas.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        comboEleccionesAbiertas = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        buttonVotar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        campoCedula = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaCandidatos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Votar");

        comboEleccionesAbiertas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEleccionesAbiertasActionPerformed(evt);
            }
        });

        jLabel1.setText("Elecciones Abiertas");

        buttonVotar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonVotar.setText("Votar");
        buttonVotar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVotarActionPerformed(evt);
            }
        });

        jLabel3.setText("Cedula Votante");

        ListaCandidatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Cedula candidato", "Nombre Candidato", "Partido Candidato"
            }
        ));
        jScrollPane1.setViewportView(ListaCandidatos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2)
                                        .addGap(149, 149, 149))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addComponent(campoCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(27, 27, 27)
                                .addComponent(comboEleccionesAbiertas, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)))
                        .addComponent(buttonVotar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboEleccionesAbiertas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(buttonVotar)))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonVotarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVotarActionPerformed
        // TODO add your handling code here:
        String cedula = campoCedula.getText();
        String[] y = this.comboEleccionesAbiertas.getSelectedItem().toString().split("-", 2);
        String h = y[0];
        int column = 0;
        int row = this.ListaCandidatos.getSelectedRow();
        String ide = this.ListaCandidatos.getModel().getValueAt(row, column).toString();

        ClsMensaje mensaje = this.controladorVoto.Votar(cedula, h, ide);
        if (mensaje != null) {
            JOptionPane.showMessageDialog(rootPane, mensaje.getDescripcion() + " " + y[1]);
            this.ObtenerInscritos();
        }

    }//GEN-LAST:event_buttonVotarActionPerformed

    private void comboEleccionesAbiertasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEleccionesAbiertasActionPerformed
        // TODO add your handling code here:
        this.ObtenerInscritos();
    }//GEN-LAST:event_comboEleccionesAbiertasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameVotar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameVotar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameVotar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameVotar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameVotar(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ListaCandidatos;
    private javax.swing.JButton buttonVotar;
    private javax.swing.JTextField campoCedula;
    private javax.swing.JComboBox<String> comboEleccionesAbiertas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
